site/dawdle/urls.py
from django.contrib import admin
from django.urls import path
from dawdle import views


app_name = 'dawdle'
urlpatterns = [
    path('', views.FrontView.as_view(), name='front'),
    path('about', views.AboutView.as_view(), name='about'),
    path('map', views.MapView.as_view(), name='map'),
    path('map/<path:player>', views.MapView.as_view(), name='player-map'),
    path('map/quest', views.MapView.as_view(), {'quest': 'quest'}, name='quest-map'),
    path('players', views.PlayerListView.as_view(), name='player-list'),
    path('player/<path:pk>', views.PlayerDetailView.as_view(), name='player-detail'),
    path('quest', views.QuestView.as_view(), name='quest'),
    path('dump', views.PlayerDumpView.as_view(), name='dump'),
]

site/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('dawdle.urls')),
    path('admin/', admin.site.urls),
]

site/dawdle/models.py
from django.db import models

class AlignmentChoices(models.TextChoices):
    GOOD = "g"
    NEUTRAL = "n"
    EVIL = "e"


class Player(models.Model):
    name = models.CharField(primary_key=True, max_length=50)
    cclass = models.CharField(max_length=30)
    pw = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    alignment = models.CharField(
        max_length=1,
        choices=AlignmentChoices.choices,
        default=AlignmentChoices.NEUTRAL
    )
    isadmin = models.BooleanField(default=False)
    online = models.BooleanField(default=False)
    nick = models.CharField(max_length=32)
    level = models.IntegerField(default=0)
    nextlvl = models.IntegerField(default=600)
    userhost = models.CharField(max_length=255)
    posx = models.IntegerField()
    posy = models.IntegerField()
    idled = models.IntegerField(default=0)
    penmessage = models.IntegerField(default=0)
    pennick = models.IntegerField(default=0)
    penpart = models.IntegerField(default=0)
    penkick = models.IntegerField(default=0)
    penquit = models.IntegerField(default=0)
    pendropped = models.IntegerField(default=0)
    penquest = models.IntegerField(default=0)
    penlogout = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    lastlogin = models.DateTimeField(auto_now_add=True)


class Ally(models.Model):
    owner = models.ForeignKey(Player, on_delete=models.CASCADE)
    slot = models.CharField(max_length=10)      # mount, sidekick, henchman
    name = models.CharField(max_length=50) # player selectable name - may be empty
    baseclass = models.CharField(max_length=30) # lizard
    fullclass = models.CharField(max_length=30) # sparkly lizard of the beyond
    alignment = models.CharField(
        max_length=1,
        choices=AlignmentChoices.choices,
        default=AlignmentChoices.NEUTRAL
    )
    level = models.IntegerField(default=0)
    nextlvl = models.IntegerField(default=600)


class Item(models.Model):
    class Meta:
        # We use this constraint for the sqlite3 REPLACE command
        constraints = [models.UniqueConstraint(name="unique_item_owner_slot", fields=["owner", "slot"])]
    owner = models.ForeignKey(Player, on_delete=models.CASCADE)
    slot = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    level = models.IntegerField()


class History(models.Model):
    owner = models.ForeignKey(Player, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=400)


class Quest(models.Model):
    mode = models.IntegerField(default=0)
    p1 = models.CharField(max_length=50)
    p2 = models.CharField(max_length=50)
    p3 = models.CharField(max_length=50)
    p4 = models.CharField(max_length=50)
    text = models.CharField(max_length=400)
    qtime = models.IntegerField(default=0)
    stage = models.IntegerField(default=0)
    dest1x = models.IntegerField(default=0)
    dest1y = models.IntegerField(default=0)
    dest2x = models.IntegerField(default=0)
    dest2y = models.IntegerField(default=0)

site/dawdle/views.py
import csv
import io
import json
import os
import time

from xml.dom import minidom

from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic, View
from django.views.decorators.vary import vary_on_headers

from PIL import Image, ImageDraw

from .models import Player, Item, Quest
from project.settings import BASE_DIR

class FrontView(generic.TemplateView):
    template_name = "dawdle/front.html"


class AboutView(generic.TemplateView):
    template_name = "dawdle/about.html"


class MapView(View):

    def _colorplayer(self, player, questors):
        if player.name in questors:
            return (0x00, 0xff, 0xe9), (0x80, 0xbb, 0xff)
        if player.online:
            return (0x00, 0x1e, 0xe9), (0x80, 0xbb, 0xff)
        return (0xaa, 0xaa, 0xaa), (0xee, 0xee, 0xee)


    def get(self, request, *args, **kwargs):
        base_map = Image.open(os.path.join(BASE_DIR, "dawdle/static/dawdle/map.png"))
        full_map = base_map.copy()
        draw = ImageDraw.Draw(full_map)

        questors = []
        q = Quest.objects.get()
        if q and q.mode != 0:
            questors = [q.p1, q.p2, q.p3, q.p4]

        if 'player' in kwargs:
            pquery = Player.objects.filter(name=kwargs['player'])
            dotsize = 5
        elif 'quest' in kwargs and questors:
            pquery = Player.objects.filter(name__in=questors)
        else:
            pquery = Player.objects
            dotsize = 3

        if q and q.mode == 2:
            if q.stage == 1:
                draw.ellipse([q.dest1x-dotsize, q.dest1y-dotsize, q.dest1x+dotsize, q.dest1y+dotsize], fill=(0xff, 0xff, 0x00))
            else:
                draw.ellipse([q.dest2x-dotsize, q.dest2y-dotsize, q.dest2x+dotsize, q.dest2y+dotsize], fill=(0xff, 0xff, 0x00))

        for p in pquery.all():
            fillcolor, strokecolor = self._colorplayer(p, questors)
            draw.ellipse([p.posx-dotsize, p.posy-dotsize, p.posx+dotsize, p.posy+dotsize],
                         outline=strokecolor,
                         fill=fillcolor)

        map_bytes = io.BytesIO()
        full_map.save(map_bytes, format="png")
        return HttpResponse(map_bytes.getvalue(), content_type='image/png')


class PlayerListView(generic.ListView):
    model = Player
    queryset = Player.objects.order_by('-level', 'nextlvl')


class PlayerDetailView(generic.DetailView):
    model = Player


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        p = self.object
        context['total_penalties'] = sum([p.penkick, p.penpart, p.penquit, p.pendropped, p.pennick, p.penmessage, p.penlogout, p.penquest])
        context['total_items'] = p.item_set.aggregate(Sum('level'))['level__sum']
        return context


class PlayerDumpView(generic.ListView):

    @vary_on_headers('Accept')
    def get(self, request, *args, **kwargs):
        response = HttpResponse()
        plist = []
        for p in Player.objects.all():
            plist.append({
                "name": p.name,
                "cclass": p.cclass,
                "idled": p.idled,
                "level": p.level,
                "nick": p.nick,
                "userhost": p.userhost,
                "email": p.email,
            })
        if request.accepts('text/plain') or request.accepts('text/csv'):
            response.content_type = 'text/csv'
            writer = csv.DictWriter(response, ('name', 'cclass', 'idled', 'level', 'nick', 'userhost', 'email'))
            writer.writeheader()
            for p in plist:
                writer.writerow(p)
        elif request.accepts('application/json'):
            response.content_type = 'application/json'
            json.dump(plist, response, separators=(',',':'))
        elif request.accepts('application/xml'):
            response.content_type = 'application/xml'
            root = minidom.Document()
            players_el = root.createElement('players')
            root.appendChild(players_el)
            for p in plist:
                el = root.createElement('player')
                for k,v in p.items():
                    el.setAttribute(k, str(v))
                players_el.appendChild(el)
            root.writexml(response)
        return response


class QuestView(generic.TemplateView):
    template_name = "dawdle/quest.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            quest = Quest.objects.get()
            questors = Player.objects.filter(name__in=[quest.p1,quest.p2,quest.p3,quest.p4]).all()
            context['quest'] = quest
            context['questors'] = questors
            context['qtime_remaining'] = quest.qtime - time.time()
        except Quest.DoesNotExist:
            context['quest'] = None
        return context

site/dawdle/templates/dawdle/about.html
{% extends "dawdle/base.html" %}

{% block content %}

<div class="contentbox">
  <h1>About DawdleRPG</h1>

  <p>DawdleRPG was made by Daniel Lowe in loving imitation of the venerable
    <a href="https://idlerpg.net/">IdleRPG</a> of IRC fame,
    by <a href="mailto:jotun@idlerpg.net">jotun@idlerpg.net</a>.</p>

  <p>Source code for both the bot and the website can be found at:
    <a href="https://github.com/dlowe-net/dawdlerpg/">https://github.com/dlowe-net/dawdlerpg/</a>.
    The code is licensed under the Apache License 2.0.</p>

</div>

{% endblock %}

site/dawdle/templates/dawdle/base.html
<html><head><title>{% block title %}DawdleRPG{% endblock %}</title>
    <style>
body {
    font-family: sans-serif;
    margin: 0;
    padding: 0;
    background: #eee;
}
#header-container {
    color: #e1cdb5;
    background: #49306b;
    margin: 0;
    padding: 0 0.5em;
}
#header {
    text-align: left;
    #height: 67px;
    padding: 0;
    margin: 0 auto;
    width: 70%;
    position: relative;
}
#header h1 {
    display: inline-block;
    margin: 0;
    line-height: 67px;
}
#header ul {
    display: inline-block;
    position: absolute;
    right: 0;
    margin: 0;
    padding: 0;
    list-style-type: none;
    height: 100%:
}
#header li {
    display: inline-block;
    margin: 0;
    line-height: 67px;
    text-align: center;
    padding-left: 1em;
    padding-right: 1em;
}
#header li:hover {
    background-color: #AF97AC;
}
#header a {
    color: #e1cdb5;
    text-decoration: none;
}
#content {
    margin: 1em auto;
    width: 75%;
}
.contentbox {
    background: white;
    margin: 2rem;
    padding: 0.5rem;
}
.contentbox h1 {
    margin-top: 0;
    padding: 0;
}
.contentbox h2 {
    margin-top: 0;
    padding: 0;
}
.good-align {
    color: #00f;
}
.evil-align {
    color: #500;
}
      @media only screen and (max-width: 1200px) {
          body {
              font-size: 200%;
              margin: 0;
              padding: 0;
          }
          #header-container {
              padding-top: 0;
              padding-bottom: 0;
          }
          #header h1 {
              display: block;
              position: relative;
              text-align: center;
          }
          #header ul {
              display: block;
              position: relative;
              margin: 0 auto;
              text-align: center;
          }
          #content {
              width: 100%;
              margin: 0;
          }
          .contentbox {
              margin: 0 0;
          }
      }

#playerlist {
  display: inline-block;
  border-collapse: collapse;
}
#playerlist tr:nth-child(even) {
  background: #E1CDB5;
}
#playerlist thead tr {
  background: #90708C;
}
#playerlist thead tr td {
  color: white;
  font-weight: bold;
  padding: 0.5rem 1rem;
}
#playerlist td {
  padding: 0.1rem 1rem;
}
#pmap-container {
  display: inline-block;
  padding: 1rem;
  vertical-align: top;
}
.online a {
  text-decoration: none;
  color: black;
}
.online a:hover {
  color: black;
  text-decoration: underline;
}
.offline {
  color: gray;
}
.offline a {
  text-decoration: none;
  color: gray;
}
.offline a:hover {
  color: gray;
  text-decoration: underline;
}
{% block extrastyles %}{% endblock %}
    </style>
  </head><body>
    <div id="header-container">
      <div id="header">
        <h1><a href="/">DawdleRPG</a></h1>
        <ul>
          <a href="{% url 'dawdle:about' %}"><li>About</li></a>
          <a href="{% url 'dawdle:player-list' %}"><li>Players</li></a>
          <a href="/quest"><li>Quest</li></a>
        </ul>
      </div>
    </div>
    <div id="content">{% block content %}{% endblock %}</div>
</body></html>

site/dawdle/templates/dawdle/front.html
{% extends "dawdle/base.html" %}

{% block content %}

<div class="contentbox">
  <h1>Welcome to DawdleRPG</h1>

  <p>DawdleRPG is an IRC game where your alter-ego goes adventuring
    across a rich land full of magic and adventure, while players lurk
    silently in a channel.  You register your character, and sit back
    and enjoy the ride, taking care not to disturb the channel.</p>

  <h2>Getting Started</h2>

  <p>To start, login to your favorite IRC network and join the
    DawdleRPG channel.  Then, send a private message to the bot:</p>

  <p><code>/msg dawdlerpg register &lt;name&gt; &lt;password&gt;
      &lt;character class&gt;</code></p>

  <p>If all goes well, your character will start at level 0 and begin
    wandering the lands.  You may explore the other commands by
    messaging <code>help</code> to the bot.</p>

  <p>If you lose connection to IRC, you should login quickly with the
    command: <code>/msg dawdlerpg login &lt;name&gt; &lt;password&gt;</code></p>

  <h2>Advancement & Penalties</h2>

  <p>Your character advances through the passage of time.  You will be
    kept updated regularly on how long your character has until the
    next level.  Events may happen to your character which will push
    you forward or back along your advancement path.</p>

  <p>As much as doing nothing on the channel is rewarded, doing
    something on the channel is punished.  Sending messages, changing
    your nick, parting the channel, getting kicked from the channel,
    quitting IRC, and using the LOGOUT command are all penalized to
    different degrees.  If you are disconnected or netsplit, your
    character will <em>not</em> be penalized as long as you login
    again within 15 minutes.</p>

  <p>Incurring a penalty may cause you to fail a quest, penalizing
    everyone online!  See below for details.</p>

  <h2>Combat and Equipment</h2>

  <p>Characters will frequently engage in combat.  Combat is resolved
    by taking the sum of item levels of each combatant, then randomly
    picking a number between 0 and that sum.  The side with the higher
    sum wins the combat.</p>

  <p>In one-on-one fights, the winner may take an item from the loser,
    giving the loser a replacement item in a moment of pity.  The
    winner might also deal a Critical Strike, which slows the loser's
    progess to the next level.  Regardless of outcome, the challenger
    may randomly find an item, and pick it up.</p>

  <p>The level of equipment found is usually limited by the level of
    the character, but there are certain rare artifacts of great
    power.  The level of these artifacts can be far beyond what a
    character may usually possess.</p>

  <h2>Alignment</h2>

  <p>Your character starts out as neutral.  By using
    the <code>ALIGN</code> command, you may change it to good or
    evil (or back to neutral, if you tire of the struggle).</p>

  <p>Good characters get a bonus to their combat power, and
    occasionally help each other to the next level.  They are more
    likely to find an item after battling. However, they are much less
    likely to deal a Critical Strike.</p>

  <p>Evil characters have a penalty to their combat power, but are
    much more likely to deal a Critical Strike.  They are less likely to
    find an item after the battle.  They will steal an item from a
    good character if they can, but are frequently forsaken by their
    evil god.</p>

  <h2>Mounts</h2>

  <p>When your character is powerful enough, they might attract a
    mount.  This mount will level with your character, but at a faster
    rate.  The mount will match your alignment, however &mdash;
    changing your alignment will cause them to leave in disgust.  Your
    mount's level adds to your prowess in battle.</p>

  <h2>Quests</h2>

  <p>The gods will occasionally pick out four characters to go on a
    Quest.  The nature of this quest may vary - sometimes a quest will
    take a certain length of time.  Sometimes the characters must
    journey together to a far-off land.  On completion of the quest,
    each questor will advance 25% of their time to next level.</p>

  <p>If any questor fails the quest, however, if they are ever
    penalized, the quest has failed, and the gods will
    punish <em>all</em> characters with a stiff penalty.</p>

</div>

{% endblock %}

site/dawdle/templates/dawdle/player_detail.html
{% extends "dawdle/base.html" %}
{% load duration %}
{% load alignment %}

{% block content %}
  <div class="contentbox">
    <h1>{{player.name}}, the level {{player.level}} {{player.cclass}}</h1>
    <table><tbody>
        <tr>
          <td>Level:</td><td>{{player.level}}</td>
          <td>Current Position:</td><td>{{player.posx}}, {{player.posy}}</td>
        </tr>
        <tr>
          <td>Account created:</td><td>{{player.created}}</td>
          <td>Last Login:</td><td>{{player.lastlogin}}</td>
        </tr>
        <tr>
          <td>Total time idled:</td><td>{{player.idled|duration}}</td>
          <td>Time to next level:</td><td>{{player.nextlvl|duration}}</td>
        </tr>
        <tr>
          <td>Alignment:</td><td><span class="{{player.alignment|alignment}}-align">{{player.alignment|alignment}}</span></td>
        </tr>
    </tbody></table>
    <img src="{% url 'dawdle:player-map' player.name %}" alt="Player Map" usemap="#playermap">
    <map name="playermap">
      <area shape="circle"
            coords="{{player.posx}},{{player.posy}},3"
            alt="{{player.name}}"
            href="{% url 'dawdle:player-detail' player.name %}">
    </map>


    </div><div class="contentbox">
    <h2>Penalties</h2>
    <table><tbody>
        <tr>
          <td>Being kicked:</td><td>{{player.penkick|duration}}</td>
          <td>Leaving channel:</td><td>{{player.penpart|duration}}</td>
        </tr>
        <tr>
          <td>Quitting:</td><td>{{player.penquit|duration}}</td>
          <td>Dropping link:</td><td>{{player.pendropped|duration}}</td>
        </tr>
        <tr>
          <td>Changing nicks:</td><td>{{player.pennick|duration}}</td>
          <td>Messaging:</td><td>{{player.penmessage|duration}}</td>
        </tr>
        <tr>
          <td>Logout command:</td><td>{{player.penlogout|duration}}</td>
          <td>Quest failures:</td><td>{{player.penquest|duration}}</td>
        </tr>
    </tbody></table>
    <p>Total penalties: {{total_penalties|duration}}</p>

    </div><div class="contentbox">
    <h2>Items</h2>
    <ul>
    {% for item in player.item_set.all|dictsort:"slot" %}
    <li>{{item.slot}}: Level {{ item.level }} {{item.name}}</li>
    {% endfor %}
    </ul>
    <p>Total item level: {{ total_items }}</p>
  </div><div class="contentbox">
    {% if player.ally_set %}
    <h2>Allies</h2>
    <ul>
    {% for ally in player.ally_set.all|dictsort:"slot" %}
    <li>{{ally.slot}}: level {{ ally.level }} {{ally.fullclass}}, Next level in {{ally.nextlvl|duration}}.</li>
    {% endfor %}
    </ul>
  </div><div class="contentbox">
    {% endif %}
    <h2>History</h2>
    <ul>
    {% for event in player.history_set.all|dictsortreversed:"time" %}
    <li>{{event.time}}: {{event.text}}</li>
    {% endfor %}
    </ul>
    </div>

{% endblock %}

site/dawdle/templates/dawdle/player_list.html
{% extends "dawdle/base.html" %}
{% load static %}
{% load duration %}
{% load alignment %}

{% block extrastyles %}
#playerlist {
  display: inline-block;
  border-collapse: collapse;
}
#playerlist tr:nth-child(even) {
  background: #E1CDB5;
}
#playerlist thead tr {
  background: #90708C;
}
#playerlist thead tr td {
  color: white;
  font-weight: bold;
  padding: 0.5rem 1rem;
}
#playerlist td {
  padding: 0.1rem 1rem;
}
#playerlist a:hover {
  color: blue;
  text-decoration: underline;
}
#pmap-container {
  display: inline-block;
  padding: 1rem;
  vertical-align: top;
}
.online a {
  text-decoration: none;
  color: black;
}
.offline {
  color: gray;
}
.online a:hover {
  color: blue;
  text-decoration: underline;
}
{% endblock %}

{% block content %}
  <div class="contentbox">
    <h1>Players</h1>

    <table id="playerlist">
      <thead>
        <tr><td>Rank</td><td style="width:30rem">Name</td><td>Time to next level</td></tr>
      </thead><tbody>
        {% for p in object_list %}
        <tr class="{%if p.online %}online{% else %}offline{% endif %}">
          <td style="text-align:right">#{{forloop.counter}}</td>
          <td><img style="height: 0.7em; width: 0.7em"
                                             src="{% if p.online %}
                                                  {% static 'dawdle/Blue_sphere.svg' %}
                                                  {% else %}
                                                  {% static 'dawdle/Gray_sphere.svg' %}
                                                  {% endif %}"
                                             alt="{% if p.online %}
                                                  On
                                                  {% else %}
                                                  Off
                                                  {% endif %}">
            <a href="{% url 'dawdle:player-detail' p.name %}">{{p.name}},
              the <span class="{{p.alignment|alignment}}-align">{{p.alignment|alignment}}</span>
            level {{p.level}} {{p.cclass}}</a>
          </td>
          <td style="text-align: right"2>{{p.nextlvl|duration}}.</td>
        </tr>
        {% endfor %}
    </tbody></table>

    <div id="pmap-container">
      <img id="pmap" src="{% url 'dawdle:map' %}" alt="Player Map" usemap="#playermap">
    </div>
    <map name="playermap">
      {% for p in object_list %}
      <area shape="circle"
            coords="{{p.posx}},{{p.posy}},3"
            alt="{{p.name}}"
            href="{% url 'dawdle:player-detail' p.name %}">
      {% endfor %}
    </map>
  </div>
{% endblock %}

site/dawdle/templates/dawdle/quest.html
{% extends "dawdle/base.html" %}
{% load static %}
{% load duration %}
{% load alignment %}

{% block content %}
<div class="contentbox">
  {% if quest and quest.mode != 0%}
  <h1>The sacred quest to {{quest.text}}</h1>

  {% if quest.mode == 1 %}
  <p>Time left in quest: {{qtime_remaining|duration}}</p>
  {% elif quest.stage == 1 %}
  <p>Questor's next destination: ({{quest.dest1x}}, {{quest.dest1y}})</p>
  {% else %}
  <p>Questor's next destination: ({{quest.dest2x}}, {{quest.dest2y}})</p>
  {% endif %}

      <table id="playerlist">
      <thead>
        <tr><td style="width:30rem">Questor</td><td>Time to next level</td></tr>
      </thead><tbody>
        {% for p in questors %}
        <tr class="{%if p.online %}online{% else %}offline{% endif %}">
          <td><img style="height: 0.7em; width: 0.7em"
                                             src="{% if p.online %}
                                                  {% static 'dawdle/Blue_sphere.svg' %}
                                                  {% else %}
                                                  {% static 'dawdle/Gray_sphere.svg' %}
                                                  {% endif %}"
                                             alt="{% if p.online %}
                                                  On
                                                  {% else %}
                                                  Off
                                                  {% endif %}">
            <a href="{% url 'dawdle:player-detail' p.name %}">{{p.name}},
              the <span class="{{p.alignment|alignment}}-align">{{p.alignment|alignment}}</span>
            level {{p.level}} {{p.cclass}}</a>
          </td>
          <td style="text-align: right"2>{{p.nextlvl|duration}}</td>
        </tr>
        {% endfor %}
      </tbody></table>

      <div id="pmap-container">
        <img id="pmap" src="{% url 'dawdle:map' %}" alt="Player Map" usemap="#playermap">
      </div>
      <map name="playermap">
        {% for p in questors %}
        <area shape="circle"
              coords="{{p.posx}},{{p.posy}},3"
              alt="{{p.name}}"
              href="{% url 'dawdle:player-detail' p.name %}">
        {% endfor %}
      </map>

      {% else %}
      <h1>No current quest</h1>
      <p>There is no decreed quest at this time.</p>
  {% endif %}
</div>

{% endblock %}